/**
 * Copyright (c) 2025 Nicolai Electronics
 * (Adapted for command-driven PIO by Gemini)
 *
 * SPDX-License-Identifier: MIT
 */
/**/
#include "rvswd.h"
#include <inttypes.h>
#include <pico/time.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "RVSWD_full.pio.h" // Generated by CMake

// PIO clock frequency (e.g., 10 MHz). 
// This gives 100ns resolution for delays.
#define PIO_CLK_HZ 100*1000*1000.0f

//
// --- PIO Helper Functions ---
//

// Reverses endianness for a 32-bit unsigned integer
uint32_t inline reverse_endian_32(uint32_t val) {
    return ((val & 0x000000FF) << 24) |
           ((val & 0x0000FF00) << 8)  |
           ((val & 0x00FF0000) >> 8)  |
           ((val & 0xFF000000) >> 24);
}


/**
 * @brief Formats and sends a command word to the PIO.
 * * Command format:
 * | 13:9 (Cmd Addr) | 8 (Dir) | 7:0 (Count-1) |
 * * @param handle RVSWD handle
 * @param cmd_offset The 5-bit PIO address offset (from pio_get_public_label)
 * @param bit_count The number of bits to transfer (0-256).
 * @param out_en The direction bit (true=write/output, false=read/input)
 */
static void rvswd_send_cmd(rvswd_handle_t* handle, uint cmd_offset, uint bit_count, bool out_en) {
    // For counts 0-256, the value is 0-255 (count-1)
    uint count_val = (bit_count == 0) ? 0 : (bit_count - 1);
    cmd_offset += handle->pio_offset;
    /*uint32_t cmd = ((count_val) & 0xff) |
                   ((uint)out_en << 8) |
                   (cmd_offset << 9);*/
    uint32_t cmd = ((uint32_t)count_val << 24) | // Bits 31:24
                   ((uint32_t)out_en << 23) |   // Bit 23
                   ((uint32_t)cmd_offset << 18); // Bits 22:18
    //printf("CMD = %08X (offset=%u, bit_count=%u, out_en=%d)\n", cmd, cmd_offset, bit_count, out_en);
    pio_sm_put_blocking(handle->pio, handle->sm, cmd);
}

/**
 * @brief Write N bits using PIO (max 32).
 */
static inline void rvswd_pio_write_bits(rvswd_handle_t* handle, uint32_t data, uint8_t bit_count) {
    // Send INVERTED data for open-drain emulation
    pio_interrupt_clear(handle->pio, 0);
    // Left-align data since PIO shifts MSB-first (shift_left=true)
    if (bit_count < 32)
        data <<= (32 - bit_count);

    //printf("TX FIFO level before cmd: %u\n", pio_sm_get_tx_fifo_level(handle->pio, handle->sm));
    rvswd_send_cmd(handle, rvswd_io_offset_write_bits, bit_count, true);
    //pio_sm_put_blocking(handle->pio, handle->sm, ~data);
    pio_sm_put_blocking(handle->pio, handle->sm, data);
    //while (!pio_interrupt_get(handle->pio, 0));
    //printf("write bits PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
}

/**
 * @brief Read N bits using PIO (max 32).
 */
static inline uint32_t rvswd_pio_read_bits(rvswd_handle_t* handle, uint8_t bit_count) {

    pio_interrupt_clear(handle->pio, 1);

    rvswd_send_cmd(handle, rvswd_io_offset_read_bits, bit_count, false);
    //while (!pio_interrupt_get(handle->pio, 1));
    uint32_t data = pio_sm_get_blocking(handle->pio, handle->sm);
    //printf("read bits PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
    /// The PIO shifts data in from the LSB (since we set shift_left=false).
    // We must shift it LEFT to MSB-align it.
    /*if (bit_count < 32) {
        // return data >> (32 - bit_count); // OLD BUG
        return data << (32 - bit_count); // NEW FIX
    }*/
    return data;
}

//
// --- Public Functions (Now PIO-based) ---
//

rvswd_result_t rvswd_pio_init(rvswd_handle_t* handle) {
    gpio_deinit(handle->swclk);
    gpio_deinit(handle->swdio);

    gpio_init(handle->swclk);
    gpio_set_function(handle->swclk, GPIO_FUNC_PIO0);

    gpio_set_drive_strength(handle->swclk, GPIO_DRIVE_STRENGTH_2MA);

    gpio_set_slew_rate(handle->swclk, GPIO_SLEW_RATE_SLOW);
    //gpio_set_dir(handle->swclk, GPIO_OUT);
    

    gpio_set_function(handle->swdio, GPIO_FUNC_PIO0);
    gpio_set_pulls(handle->swdio, true, false);       // Internal pull-up (~50kΩ)
    //gpio_set_dir(handle->swdio, GPIO_IN); //Hi-Z at init

    gpio_set_drive_strength(handle->swdio, GPIO_DRIVE_STRENGTH_2MA);

    gpio_set_slew_rate(handle->swdio, GPIO_SLEW_RATE_SLOW);

    // 1. Claim PIO resources
    handle->pio = pio0; // Or pio1
    handle->sm = pio_claim_unused_sm(handle->pio, true);
    handle->pio_offset = pio_add_program(handle->pio, &rvswd_io_program);


    // 3. Configure the state machine
    pio_sm_config c = rvswd_io_program_get_default_config(handle->pio_offset);

    // Pin mapping
    sm_config_set_out_pins(&c, handle->swdio, 1);
    sm_config_set_set_pins(&c, handle->swdio, 1);  // For 'set pindirs'
    sm_config_set_in_pins(&c, handle->swdio);
    sm_config_set_sideset_pins(&c, handle->swclk);

    // Clock divider (e.g., 125MHz / 10MHz = 12.5)
    float pio_clk_div = (float)clock_get_hz(clk_sys) / PIO_CLK_HZ;
    pio_clk_div=10;
    sm_config_set_clkdiv(&c, pio_clk_div);

    // FIFO configuration
    // We want MSB-first, so shift_right=false
    sm_config_set_out_shift(&c, false, false, 32);
    sm_config_set_in_shift(&c, false, false, 32);

    // 4. Initialize GPIOs for PIO
    pio_gpio_init(handle->pio, handle->swclk);
    pio_gpio_init(handle->pio, handle->swdio);
    // MUST keep the pull-up on swdio
    gpio_set_pulls(handle->swdio, true, false); 
    
    // 5. Set initial pin states for PIO
    // 'out' value is always 0 (for driving low)
    //pio_sm_set_out_pins(handle->pio, handle->sm, handle->swdio, 1);
    // 'pindir' is 0 (input) initially
    pio_sm_set_consecutive_pindirs(handle->pio, handle->sm, handle->swdio, 1, true);
    // 'swclk' is an output
    pio_sm_set_consecutive_pindirs(handle->pio, handle->sm, handle->swclk, 1, true);

    // 6. Load config, jump to dispatcher, and start
    pio_sm_init(handle->pio, handle->sm, handle->pio_offset, &c);
    
    uint entry_point = handle->pio_offset + rvswd_io_offset_get_next_cmd;
    pio_sm_exec(handle->pio, handle->sm, entry_point);
    pio_sm_set_enabled(handle->pio, handle->sm, true);

    return RVSWD_OK;
}
 
// The bit-bang functions are now just PIO commands
rvswd_result_t inline rvswd_pio_start(rvswd_handle_t* handle) {

    gpio_put(handle->logic_helper_pin, 1);
    rvswd_send_cmd(handle, rvswd_io_offset_start, 0, true);
    
    gpio_put(handle->logic_helper_pin, 0);
    return RVSWD_OK;
}
 
rvswd_result_t inline rvswd_pio_stop(rvswd_handle_t* handle) {

    gpio_put(handle->logic_helper_pin, 1);
    rvswd_send_cmd(handle, rvswd_io_offset_stop, 0, true);
    
    gpio_put(handle->logic_helper_pin, 0);
    return RVSWD_OK;
}
 
rvswd_result_t rvswd_pio_reset(rvswd_handle_t* handle) {
    rvswd_send_cmd(handle, rvswd_io_offset_reset, 300, true);
    return RVSWD_OK;
}
 
// These functions are no longer needed
// void rvswd_write_bit(rvswd_handle_t* handle, bool value) { ... }
// bool rvswd_read_bit(rvswd_handle_t* handle) { ... }
 
//
// --- PIO-Accelerated Protocol Functions ---
// (These are now much cleaner)
//

rvswd_result_t inline rvswd_pio_write(rvswd_handle_t* handle, uint8_t reg, uint32_t value) {
    rvswd_pio_start(handle);
 
    // ADDR HOST
    bool parity = false;
    uint32_t packet = (uint32_t)reg & 0x7F; // 7 bits reg
    for (uint8_t i = 0; i < 7; i++) {
        if ((packet >> (6-i)) & 1) parity = !parity;
    }
 
    // Operation: write (1 bit)
    packet = (packet << 1) | 1;
    parity = !parity;
 
    // Parity bit (1 bit)
    packet = (packet << 1) | (parity ? 1 : 0);

    rvswd_pio_write_bits(handle, packet, 9);
 
    // Turnaround (5 bits)
    rvswd_pio_write_bits(handle, 0b10101, 5);
 
    // Data (32 bits)
    parity = false;
    for (uint8_t i = 0; i < 32; i++) {
        if ((value >> (31-i)) & 1) parity = !parity;
    }
    rvswd_pio_write_bits(handle, value, 32);

    // Parity bit (1 bit)
    rvswd_pio_write_bits(handle, (parity ? 1 : 0), 1);
 
    // Trailer (5 bits)
    rvswd_pio_write_bits(handle, 0b10111, 5);
 
    rvswd_pio_stop(handle);
 
    return RVSWD_OK;
}
 
rvswd_result_t inline rvswd_pio_read(rvswd_handle_t* handle, uint8_t reg, uint32_t* value) {
    bool parity;
 
    rvswd_pio_start(handle);
 
    // ADDR HOST
    parity = false;
    uint32_t packet = (uint32_t)reg & 0x7F; // 7 bits reg
    for (uint8_t i = 0; i < 7; i++) {
        if ((packet >> (6-i)) & 1) parity = !parity;
    }
 
    // Operation: read (1 bit)
    packet = (packet << 1) | 0;
 
    // Parity bit (1 bit)
    packet = (packet << 1) | (parity ? 1 : 0);

    rvswd_pio_write_bits(handle, packet, 9);

    // Turnaround (5 bits)
    rvswd_pio_write_bits(handle, 0b10101, 5);
 
    // Data (32 bits)
    *value = rvswd_pio_read_bits(handle, 32);
 
    // Parity bit (1 bit)
    bool parity_read = (rvswd_pio_read_bits(handle, 1) & 1);

    // Trailer (5 bits)
    rvswd_pio_write_bits(handle, 0b10111, 5);
 
    rvswd_pio_stop(handle);
 
    // Check data parity
    bool data_parity = false;
    for (uint8_t i = 0; i < 32; i++) {
        if ((*value >> (31-i)) & 1) data_parity = !data_parity;
    }
 
    return (data_parity == parity_read) ? RVSWD_OK : RVSWD_FAIL;
}

#include <stdint.h>

/**
 * @brief Calculate parity for the packet (usually ODD for Host in this format).
 */
static inline uint8_t rvswd_calc_parity(uint64_t val) {
    val ^= val >> 32;
    val ^= val >> 16;
    val ^= val >> 8;
    val ^= val >> 4;
    val &= 0xf;
    uint8_t even = (0x6996 >> val) & 1;
    return !even; // ODD parity
}

/**
 * @brief Write a 32-bit value to a debug register (MSB First).
 */
rvswd_result_t inline rvswd_pio_write_(rvswd_handle_t* handle, uint8_t reg, uint32_t value) {
    uint8_t op = 2; // Write
    
    rvswd_pio_start(handle);
    
    // 1. Address (7 bits) - Send MSB of the 7-bit field first
    rvswd_pio_write_bits(handle, (uint32_t)(reg & 0x7F), 7);
    
    // 2. Data (32 bits) - MSB first
    rvswd_pio_write_bits(handle, value, 32);
    
    // 3. Operation (2 bits)
    rvswd_pio_write_bits(handle, (uint32_t)(op & 0x03), 2);
    
    // 4. Parity (1 bit)
    // Parity is calculated over the whole sequence
    uint64_t full_packet = ((uint64_t)(reg & 0x7F) << 34) | ((uint64_t)value << 2) | (op & 0x03);
    rvswd_pio_write_bits(handle, rvswd_calc_parity(full_packet), 1);
    
    rvswd_pio_stop(handle);
    return RVSWD_OK;
}

// Helper: Standard bit-counting parity (returns 1 if number of bits is odd)
static inline uint8_t calc_parity_bit(uint64_t val) {
    val ^= val >> 32;
    val ^= val >> 16;
    val ^= val >> 8;
    val ^= val >> 4;
    val &= 0xf;
    return (0x6996 >> val) & 1;
}
void rvswd_auto_fuzz_read(rvswd_handle_t* handle, uint8_t test_reg) {
    printf("Starting RVSWD Auto-Fuzz on Register 0x%02X...\n", test_reg);
    printf("------------------------------------------------------------\n");
    printf("MSB | H-Par | T-Par | OP | Result\n");
    printf("------------------------------------------------------------\n");

    for (int msb = 1; msb >= 0; msb--) {              // Try MSB first, then LSB
        for (int h_parity = 0; h_parity <= 1; h_parity++) { // 0=Even, 1=Odd
            for (int t_parity = 0; t_parity <= 1; t_parity++) { // 0=Even, 1=Odd
                for (int op = 0; op <= 3; op++) {    // Try all opcodes 0-3
                    
                    uint32_t rx_data = 0;
                    uint64_t payload = 0;
                    
                    // 1. Construct Host Request
                    if (msb) {
                        payload = ((uint64_t)(test_reg & 0x7F) << 34) | (uint64_t)(op & 0x03);
                    } else {
                        payload = (test_reg & 0x7F) | ((uint64_t)(op & 0x03) << 39);
                    }

                    uint8_t p_bit = calc_parity_bit(payload);
                    if (h_parity) p_bit = !p_bit; // Apply Odd if requested

                    // 2. Execute Hardware Transaction
                    rvswd_pio_start(handle);
                    
                    if (msb) {
                        rvswd_pio_write_bits(handle, (uint32_t)(payload >> 9), 32); 
                        rvswd_pio_write_bits(handle, (uint32_t)(payload & 0x1FF), 9);
                    } else {
                        rvswd_pio_write_bits(handle, (uint32_t)payload, 32);
                        rvswd_pio_write_bits(handle, (uint32_t)(payload >> 32), 9);
                    }
                    rvswd_pio_write_bits(handle, p_bit, 1);

                    // 3. Capture Response
                    uint8_t  rx_addr   = (uint8_t)rvswd_pio_read_bits(handle, 7);
                    uint32_t data      = rvswd_pio_read_bits(handle, 32);
                    uint8_t  rx_status = (uint8_t)rvswd_pio_read_bits(handle, 2);
                    uint8_t  rx_parity = (uint8_t)rvswd_pio_read_bits(handle, 1);
                    
                    rvswd_pio_stop(handle);

                    // 4. Verify Target Parity
                    uint64_t rx_payload;
                    if (msb) {
                        rx_payload = ((uint64_t)rx_addr << 34) | ((uint64_t)data << 2) | rx_status;
                    } else {
                        rx_payload = rx_addr | ((uint64_t)data << 7) | ((uint64_t)rx_status << 39);
                    }
                    
                    uint8_t check = calc_parity_bit(rx_payload);
                    if (t_parity) check = !check;

                    // 5. Print Results
                    printf(" %d  |   %s   |   %s   |  %d | ", 
                           msb, h_parity ? "ODD" : "EVN", t_parity ? "ODD" : "EVN", op);

                    if (check != rx_parity) {
                        printf("FAIL: Parity Error (Got %d, Calc %d)\n", rx_parity, check);
                    } else if (rx_status != 0) {
                        printf("FAIL: Status %d (Busy/Err) Data: 0x%08X\n", rx_status, data);
                    } else if (data == 0x00000000 || data == 0xFFFFFFFF) {
                        printf("WARN: Valid Parity, but Data is 0x%08X (Bus Floating?)\n", data);
                    } else {
                        printf("SUCCESS! Data: 0x%08X\n", data);
                    }
                }
            }
        }
    }
    printf("------------------------------------------------------------\n");
}
/**
 * @brief Read a 32-bit value from a debug register (MSB First).
 */
rvswd_result_t inline rvswd_pio_read_(rvswd_handle_t* handle, uint8_t reg, uint32_t* value) {
    /*uint8_t op = 1; // Read
    
    rvswd_pio_start(handle);
    
    // --- Host Phase ---
    rvswd_pio_write_bits(handle, (uint32_t)(reg & 0x7F), 7);
    rvswd_pio_write_bits(handle, 0, 32); // Dummy data
    rvswd_pio_write_bits(handle, (uint32_t)(op & 0x03), 2);
    
    uint64_t host_packet = ((uint64_t)(reg & 0x7F) << 34) | (op & 0x03);
    rvswd_pio_write_bits(handle, rvswd_calc_parity(host_packet), 1);

    // --- Target Phase (PIO goes High-Z automatically) ---
    uint8_t  rx_addr   = (uint8_t)rvswd_pio_read_bits(handle, 7);
    uint32_t rx_data   = rvswd_pio_read_bits(handle, 32);
    uint8_t  rx_status = (uint8_t)rvswd_pio_read_bits(handle, 2);
    uint8_t  rx_parity = (uint8_t)rvswd_pio_read_bits(handle, 1);
    
    rvswd_pio_stop(handle);

    // Verify Target Parity (Target usually uses even parity in MSB mode)
    uint64_t rx_payload = ((uint64_t)rx_addr << 34) | ((uint64_t)rx_data << 2) | (rx_status);
    printf("%08X %08X %08X %02X\n", rx_addr, rx_data, rx_status, rx_parity);
    if (!rvswd_calc_parity(rx_payload) != rx_parity) {
        return RVSWD_PARITY_ERROR;
    }

    if (rx_status != 0) return RVSWD_FAIL;

    *value = rx_data;
    uint64_t data_rcvd = rvswd_pio_read_bits(handle, 64);
    printf("%16llX\n", data_rcvd);*/
    rvswd_auto_fuzz_read(handle, reg);
    return RVSWD_OK;
}
