// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// rvswd_io //
// -------- //

#define rvswd_io_wrap_target 0
#define rvswd_io_wrap 24
#define rvswd_io_pio_version 0

#define rvswd_io_BIT_DELAY 7
#define rvswd_io_DELAY_1US 7

#define rvswd_io_offset_get_next_cmd 0u
#define rvswd_io_offset_write_bits 4u
#define rvswd_io_offset_read_bits 11u
#define rvswd_io_offset_start 16u
#define rvswd_io_offset_stop 21u

static const uint16_t rvswd_io_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0x6028, //  1: out    x, 8
    0x6081, //  2: out    pindirs, 1
    0x60a5, //  3: out    pc, 5
    0x80a0, //  4: pull   block
    0xa003, //  5: mov    pins, null
    0x7781, //  6: out    pindirs, 1      side 0 [7]
    0xbf42, //  7: nop                    side 1 [7]
    0x0046, //  8: jmp    x--, 6
    0x0000, //  9: jmp    0
    0xa042, // 10: nop
    0xf780, // 11: set    pindirs, 0      side 0 [7]
    0x5f01, // 12: in     pins, 1         side 1 [7]
    0x004a, // 13: jmp    x--, 10
    0x8020, // 14: push   block
    0x0000, // 15: jmp    0
    0xff80, // 16: set    pindirs, 0      side 1 [7]
    0xff80, // 17: set    pindirs, 0      side 1 [7]
    0xff81, // 18: set    pindirs, 1      side 1 [7]
    0xb742, // 19: nop                    side 0 [7]
    0x0000, // 20: jmp    0
    0xff81, // 21: set    pindirs, 1      side 1 [7]
    0xff81, // 22: set    pindirs, 1      side 1 [7]
    0xff80, // 23: set    pindirs, 0      side 1 [7]
    0x0000, // 24: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rvswd_io_program = {
    .instructions = rvswd_io_program_instructions,
    .length = 25,
    .origin = -1,
    .pio_version = rvswd_io_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rvswd_io_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rvswd_io_wrap_target, offset + rvswd_io_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

