/**
 * Copyright (c) 2025 Nicolai Electronics
 * (Adapted for command-driven PIO by Gemini)
 *
 * SPDX-License-Identifier: MIT
 */
/**/
#include "rvswd.h"
#include <inttypes.h>
#include <pico/time.h>
#include <stdint.h>
#include <stdio.h>
#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "RVSWD_full.pio.h" // Generated by CMake

// PIO clock frequency (e.g., 10 MHz). 
// This gives 100ns resolution for delays.
#define PIO_CLK_HZ 10000000.0f

//
// --- PIO Helper Functions ---
//

/**
 * @brief Formats and sends a command word to the PIO.
 * * Command format:
 * | 13:9 (Cmd Addr) | 8 (Dir) | 7:0 (Count-1) |
 * * @param handle RVSWD handle
 * @param cmd_offset The 5-bit PIO address offset (from pio_get_public_label)
 * @param bit_count The number of bits to transfer (0-256).
 * @param out_en The direction bit (true=write/output, false=read/input)
 */
static void rvswd_send_cmd(rvswd_handle_t* handle, uint cmd_offset, uint bit_count, bool out_en) {
    // For counts 0-256, the value is 0-255 (count-1)
    uint32_t count_val = (bit_count == 0) ? 0 : (bit_count - 1);

    /*uint32_t cmd = ((count_val) & 0xff) |
                   ((uint)out_en << 8) |
                   (cmd_offset << 9);*/
    uint32_t cmd = ((uint32_t)count_val << 24) | ((uint32_t)out_en << 23) | ((uint32_t)cmd_offset << 18);
    printf("CMD = %08X (offset=%u, bit_count=%u, out_en=%d)\n", cmd, cmd_offset, bit_count, out_en);
    pio_sm_put_blocking(handle->pio, handle->sm, cmd);
}

/**
 * @brief Write N bits using PIO (max 32).
 */
static void rvswd_pio_write_bits(rvswd_handle_t* handle, uint32_t data, uint8_t bit_count) {
    // Send INVERTED data for open-drain emulation

    printf("TX FIFO level before cmd: %u\n", pio_sm_get_tx_fifo_level(handle->pio, handle->sm));
    rvswd_send_cmd(handle, handle->offset_write_bits, bit_count, true);
    pio_sm_put_blocking(handle->pio, handle->sm, ~data);
    printf("write bits PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
}

/**
 * @brief Read N bits using PIO (max 32).
 */
static uint32_t rvswd_pio_read_bits(rvswd_handle_t* handle, uint8_t bit_count) {
    rvswd_send_cmd(handle, handle->offset_read_bits, bit_count, false);
    printf("RX FIFO after CMD: %08X\n", pio_sm_get_rx_fifo_level(handle->pio, handle->sm) );
    printf("read bits PC before get = %d\n", pio_sm_get_pc(pio0, handle->sm));
    uint32_t data = pio_sm_get_blocking(handle->pio, handle->sm);
    printf("read bits PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
    // The PIO shifts data into the LSB. We shift it up to be
    // MSB-aligned to match the original bit-bang code's logic.
    if (bit_count < 32) {
        return data >> (32 - bit_count);
    }
    return data;
}

//
// --- Public Functions (Now PIO-based) ---
//

rvswd_result_t rvswd_pio_init(rvswd_handle_t* handle) {
    gpio_deinit(handle->swclk);
    gpio_deinit(handle->swdio);

    gpio_init(handle->swclk);
    gpio_set_function(handle->swclk, GPIO_FUNC_PIO0);
    gpio_set_dir(handle->swclk, GPIO_OUT);
    

    gpio_set_function(handle->swdio, GPIO_FUNC_PIO0);
    gpio_set_pulls(handle->swdio, true, false);       // Internal pull-up (~50kΩ)
    gpio_set_dir(handle->swdio, GPIO_IN); //Hi-Z at init

    // 1. Claim PIO resources
    handle->pio = pio0; // Or pio1
    handle->sm = pio_claim_unused_sm(handle->pio, true);
    handle->pio_offset = pio_add_program(handle->pio, &rvswd_io_program);

    // 2. Cache the command label offsets
    handle->offset_write_bits = rvswd_io_offset_write_bits;
    handle->offset_read_bits = rvswd_io_offset_read_bits;
    handle->offset_start = rvswd_io_offset_start;
    handle->offset_stop = rvswd_io_offset_stop;
    printf("offset_write_bits = %d\n", handle->offset_write_bits);
    //handle->offset_reset = pio_get_public_label(&rvswd_io_program, "reset");

    // 3. Configure the state machine
    pio_sm_config c = rvswd_io_program_get_default_config(handle->pio_offset);

    // Pin mapping
    sm_config_set_out_pins(&c, handle->swdio, 1);
    sm_config_set_set_pins(&c, handle->swdio, 1);  // For 'set pindirs'
    sm_config_set_in_pins(&c, handle->swdio);
    sm_config_set_sideset_pins(&c, handle->swclk);

    // Clock divider (e.g., 125MHz / 10MHz = 12.5)
    float pio_clk_div = (float)clock_get_hz(clk_sys) / PIO_CLK_HZ;
    sm_config_set_clkdiv(&c, pio_clk_div);

    // FIFO configuration
    // We want MSB-first, so shift_right=false
    sm_config_set_out_shift(&c, false, false, 32);
    sm_config_set_in_shift(&c, false, false, 32);

    // 4. Initialize GPIOs for PIO
    pio_gpio_init(handle->pio, handle->swclk);
    pio_gpio_init(handle->pio, handle->swdio);
    // MUST keep the pull-up on swdio
    gpio_set_pulls(handle->swdio, true, false); 
    
    // 5. Set initial pin states for PIO
    // 'out' value is always 0 (for driving low)
    pio_sm_set_out_pins(handle->pio, handle->sm, handle->swdio, 1);
    // 'pindir' is 0 (input) initially
    pio_sm_set_consecutive_pindirs(handle->pio, handle->sm, handle->swdio, 1, false);
    // 'swclk' is an output
    pio_sm_set_consecutive_pindirs(handle->pio, handle->sm, handle->swclk, 1, true);

    // 6. Load config, jump to dispatcher, and start
    pio_sm_init(handle->pio, handle->sm, handle->pio_offset, &c);
    
    uint entry_point = handle->pio_offset + rvswd_io_offset_get_next_cmd;
    pio_sm_exec(handle->pio, handle->sm, entry_point);
    pio_sm_set_enabled(handle->pio, handle->sm, true);

    return RVSWD_OK;
}
 
// The bit-bang functions are now just PIO commands
rvswd_result_t rvswd_pio_start(rvswd_handle_t* handle) {
    rvswd_send_cmd(handle, handle->offset_start, 0, false);
    printf("start PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
    return RVSWD_OK;
}
 
rvswd_result_t rvswd_pio_stop(rvswd_handle_t* handle) {
    rvswd_send_cmd(handle, handle->offset_stop, 0, false);
    printf("stop PC = %d\n", pio_sm_get_pc(pio0, handle->sm));
    return RVSWD_OK;
}
 
rvswd_result_t rvswd_pio_reset(rvswd_handle_t* handle) {
    //rvswd_send_cmd(handle, handle->offset_reset, 0, false);
    return RVSWD_OK;
}
 
// These functions are no longer needed
// void rvswd_write_bit(rvswd_handle_t* handle, bool value) { ... }
// bool rvswd_read_bit(rvswd_handle_t* handle) { ... }
 
//
// --- PIO-Accelerated Protocol Functions ---
// (These are now much cleaner)
//

rvswd_result_t rvswd_pio_write(rvswd_handle_t* handle, uint8_t reg, uint32_t value) {
    rvswd_pio_start(handle);
 
    // ADDR HOST
    bool parity = false;
    uint32_t packet = (uint32_t)reg & 0x7F; // 7 bits reg
    for (uint8_t i = 0; i < 7; i++) {
        if ((packet >> (6-i)) & 1) parity = !parity;
    }
 
    // Operation: write (1 bit)
    packet = (packet << 1) | 1;
    parity = !parity;
 
    // Parity bit (1 bit)
    packet = (packet << 1) | (parity ? 1 : 0);

    rvswd_pio_write_bits(handle, packet, 9);
 
    // Turnaround (5 bits)
    rvswd_pio_write_bits(handle, 0b01010, 5);
 
    // Data (32 bits)
    parity = false;
    for (uint8_t i = 0; i < 32; i++) {
        if ((value >> (31-i)) & 1) parity = !parity;
    }
    rvswd_pio_write_bits(handle, value, 32);

    // Parity bit (1 bit)
    rvswd_pio_write_bits(handle, (parity ? 1 : 0), 1);
 
    // Trailer (5 bits)
    rvswd_pio_write_bits(handle, 0b11101, 5);
 
    rvswd_pio_stop(handle);
 
    return RVSWD_OK;
}
 
rvswd_result_t rvswd_pio_read(rvswd_handle_t* handle, uint8_t reg, uint32_t* value) {
    bool parity;
 
    rvswd_pio_start(handle);
 
    // ADDR HOST
    parity = false;
    uint32_t packet = (uint32_t)reg & 0x7F; // 7 bits reg
    for (uint8_t i = 0; i < 7; i++) {
        if ((packet >> (6-i)) & 1) parity = !parity;
    }
 
    // Operation: read (1 bit)
    packet = (packet << 1) | 0;
 
    // Parity bit (1 bit)
    packet = (packet << 1) | (parity ? 1 : 0);

    rvswd_pio_write_bits(handle, packet, 9);

    // Turnaround (5 bits)
    rvswd_pio_write_bits(handle, 0b01010, 5);
 
    // Data (32 bits)
    *value = rvswd_pio_read_bits(handle, 32);
 
    // Parity bit (1 bit)
    bool parity_read = (rvswd_pio_read_bits(handle, 1) & 1);

    // Trailer (5 bits)
    rvswd_pio_write_bits(handle, 0b11101, 5);
 
    rvswd_pio_stop(handle);
 
    // Check data parity
    bool data_parity = false;
    for (uint8_t i = 0; i < 32; i++) {
        if ((*value >> (31-i)) & 1) data_parity = !data_parity;
    }
 
    return (data_parity == parity_read) ? RVSWD_OK : RVSWD_FAIL;
}