// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// rvswd_io //
// -------- //

#define rvswd_io_wrap_target 0
#define rvswd_io_wrap 26
#define rvswd_io_pio_version 0

#define rvswd_io_BIT_DELAY 2

#define rvswd_io_offset_get_next_cmd 0u
#define rvswd_io_offset_write_bits 4u
#define rvswd_io_offset_read_bits 10u
#define rvswd_io_offset_start 15u
#define rvswd_io_offset_stop 18u
#define rvswd_io_offset_reset 22u

static const uint16_t rvswd_io_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1
    0x6028, //  1: out    x, 8
    0x6081, //  2: out    pindirs, 1
    0x60a5, //  3: out    pc, 5
    0x80a0, //  4: pull   block
    0x7201, //  5: out    pins, 1         side 0 [2]
    0xba42, //  6: nop                    side 1 [2]
    0x0045, //  7: jmp    x--, 5
    0x0000, //  8: jmp    0
    0xb842, //  9: nop                    side 1
    0xb242, // 10: nop                    side 0 [2]
    0x5a01, // 11: in     pins, 1         side 1 [2]
    0x004a, // 12: jmp    x--, 10
    0x8020, // 13: push   block
    0x0000, // 14: jmp    0
    0xfa01, // 15: set    pins, 1         side 1 [2]
    0xfa00, // 16: set    pins, 0         side 1 [2]
    0x0000, // 17: jmp    0
    0xfa00, // 18: set    pins, 0         side 1 [2]
    0xfa01, // 19: set    pins, 1         side 1 [2]
    0xe080, // 20: set    pindirs, 0
    0x0000, // 21: jmp    0
    0xfa01, // 22: set    pins, 1         side 1 [2]
    0xb242, // 23: nop                    side 0 [2]
    0xba42, // 24: nop                    side 1 [2]
    0x0057, // 25: jmp    x--, 23
    0x0012, // 26: jmp    18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rvswd_io_program = {
    .instructions = rvswd_io_program_instructions,
    .length = 27,
    .origin = -1,
    .pio_version = rvswd_io_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rvswd_io_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rvswd_io_wrap_target, offset + rvswd_io_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

